# Generate Trophy Card Workflow

name: Generate Trophy Card

on:
  schedule:
    # Execute every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate trophy.svg
        uses: soulteary/github-profile-trophy-action@v1.0.0
        with:
          options: "username=${{ github.repository_owner }}&theme=dracula&column=8&row=1&margin-w=8&margin-h=8&no-bg=false&no-frame=false"
          path: dist/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push trophy.svg to trophy-output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: trophy-output

